name: 'origami-version'
description: 'Create a SemVer git tag and GitHub release based on the semver label a merged pull-request has.'
inputs:
  change-api-key:
    description: 'The x-api-key header value for authenticating the request to Change API. Create a key by following the instructions here https://docs.google.com/document/d/1Ju84f1jtAmxmHtsyGfcyxdG3ZWrhuN9GrNnBxjVWhi4/edit'
    required: true
  system-code:
    description: The systemcode of the system being changed.
    required: true
  environment:
    description: The environment in which the system is being changed.
    required: true
  slack-channels:
    description: Comma-separated list of Slack channel names for notifications.
    required: false
  extra-properties: 
    required: false
runs:
  using: 'node12'
  main: 'index.js'